# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/beyond0lte/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),beyond0lte)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-G970F,f528af82d21a682876e52c64f842a1fe004188b4)
$(call add-radio-file-sha1-checked,radio/cm.bin_SM-G970N,bc9a3f38594368080affb6b1546b02488e12cd08)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-G970F,852b89cd8b13b7ad5758cec058e0ddcdf27144eb)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-G970N,85468073397fb608bc57ed769e6eecff13e4e53c)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-G970F,6ecce74dc01d82678c1756b551abc1cf59e5de8e)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-G970N,899581095247329d8bc9a0dac8719ec48cd4201d)
$(call add-radio-file-sha1-checked,radio/models,3ccf54b4274f3d86e88fd21709447651ba68cef4)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-G970F,9b99e0ef07bfbfd8eed549f25178d8090c6a9c88)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-G970N,82acc906ea3cc31ce45e811e1ea4296dc8d331f9)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-G970F,4c834c2cdde3a16df87d1c5e08d8d989c1f7ba64)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-G970N,ab82bbd04736376f9bf8f28050ee434c91a2d740)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-G970F,d4eea2c9206286ac80ea19ae5309cb1e598b38cd)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-G970N,b4da5877429da8b4debc104981f84a1b022ad843)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-G970F,429a7d45a5b22d4e71311911725f68d345007a4b)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-G970N,3f90617560c6006698a28dd562f2dfc1ab0ef57b)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-G970F,c760ce08a5de99d1b7a2ebd3d29b65b4609bb773)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-G970N,b431d71a8b976fc76d76be062f663de28d2e79bb)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-G970F,7a314c30935fa34e67d61e24e42d4b55c5581805)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-G970N,dfeda461eda2bfea5ee2f9531954e1bb1b3b72c5)
$(call add-radio-file-sha1-checked,radio/version_SM-G970F,115370c8e08fb70469c0c9adc1b38d8206114252)
$(call add-radio-file-sha1-checked,radio/version_SM-G970N,90297cf295c482d95c8a2bb39750dca3f408697f)

endif
